bookthedoctor/Models/PatientViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BookMyDoctor.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    namespace BookMyDoctor.Models
    {
        public class ExternalLoginConfirmationViewModel
        {
            [Required]
            [Display(Name = "Email")]
            public string Email { get; set; }
        }

        public class ExternalLoginListViewModel
        {
            public string ReturnUrl { get; set; }
        }

        public class SendCodeViewModel
        {
            public string SelectedProvider { get; set; }
            public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
            public string ReturnUrl { get; set; }
            public bool RememberMe { get; set; }
        }

        public class VerifyCodeViewModel
        {
            [Required]
            public string Provider { get; set; }

            [Required]
            [Display(Name = "Code")]
            public string Code { get; set; }
            public string ReturnUrl { get; set; }

            [Display(Name = "Remember this browser?")]
            public bool RememberBrowser { get; set; }

            public bool RememberMe { get; set; }
        }

        public class ForgotViewModel
        {
            [Required]
            [Display(Name = "Email")]
            public string Email { get; set; }
        }

        public class LoginViewModel
        {
            [Required]
            [Display(Name = "Email")]
            [EmailAddress]
            public string Email { get; set; }

            [Required]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            [Display(Name = "Remember me?")]
            public bool RememberMe { get; set; }
        }

        public class RegisterViewModel
        {
           
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }

            
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Confirm password")]
            [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }

            [StringLength(100, ErrorMessage = "The {0} must be at least {6} characters long.", MinimumLength = 6)]

            public string Name;
            public int PhoneNumber;
            public string PatientID;


        }

        public class ResetPasswordViewModel
        {
            [Required]
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }

            [Required]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Confirm password")]
            [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }

            public string Code { get; set; }
        }

        public class ForgotPasswordViewModel
        {
            [Required]
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }
        }
    }

}

bookthedoctor/Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace bookthedoctor.Controllers
{
    public class PatientController : Controller
    {
        // GET: Patient
        public ActionResult Index()
        {
            return View();
        }

        // GET: Patient/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Patient/Create
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult SelectDoctor()
        {
            return View();
        }

        public ActionResult ViewDoctorDetails()
        {
            return View();
        }
        public ActionResult TakeAppoitment()
        {
            return View();
        }

        public ActionResult CardiologistsDetails()
        {
            return View();
        }

        public ActionResult ChildSpecialistDetails()
        {
            return View();
        }

        public ActionResult DermatologistDetails()
        {
            return View();
        }
        public ActionResult GynecologistDetails()
        {
            return View();
        }








        // POST: Patient/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Patient/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Patient/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Patient/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Patient/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

bookthedoctor/Views/Patient/CardiologistsDetails.cshtml
@model BookMyDoctor.Models.BookMyDoctor.Models.RegisterViewModel

@{
    ViewBag.Title = "CardiologistsDetails";
}


<h2><br />Following doctors are avalible for you</h2>

<div style="width:500px;height:100px;border:1px solid #000;">
    <p style="padding-left:50px;">
        Name: Dr. Maham<br />
        Specification :Cardiologist<br />
        Clinic: Model Town<br />
        Hospital:GangaRam Hospital Mall Road<br />
        @Html.ActionLink("Take Appoitment", "TakeAppoitment", "Patient")

    </p>
</div>

<div style="width:500px;height:100px;border:1px solid #000;">
    <p style="padding-left:50px;">
        Name: Dr. Hiba<br />
        Specification :Cardiologist<br />
        Clinic: Wapda Town<br />
        Hospital:Fatima Memorial Hospital<br />
        @Html.ActionLink("Take Appoitment", "TakeAppoitment", "Patient")

        </pstyle="padding-left:50px;>
</div>

<div style="width:500px;height:100px;border:1px solid #000;">
    <p style="padding-left:50px;">
        Name: Dr. Khadija<br />
        Specification :Cardiologist<br />
        Clinic: GT road<br />
        Hospital:Fatima Memorial Hospital<br />
        @Html.ActionLink("Take Appoitment", "TakeAppoitment", "Patient")

    </p>
</div>

@Html.ActionLink("Back", "SelectDoctor", "Patient")

bookthedoctor/Views/Patient/ChildSpecialistDetails.cshtml
@model BookMyDoctor.Models.BookMyDoctor.Models.RegisterViewModel

@{
    ViewBag.Title = "ChildSpecialistDetails";
}

<h2><br />Following doctors are avalible for you</h2>

<div style="width:500px;height:100px;border:1px solid #000;">
    <p style="padding-left:50px;">
        Name: Dr. Maham<br />
        Specification :Child Specialist<br />
        Clinic: Model Town<br />
        Hospital:GangaRam Hospital Mall Road<br />
        @Html.ActionLink("Take Appoitment", "TakeAppoitment", "Patient")

    </p>
</div>

<div style="width:500px;height:100px;border:1px solid #000;">
    <p style="padding-left:50px;">
        Name: Dr. Hiba<br />
        Specification :Child Specialist<br />
        Clinic: Wapda Town<br />
        Hospital:Fatima Memorial Hospital<br />
        @Html.ActionLink("Take Appoitment", "TakeAppoitment", "Patient")

        </pstyle="padding-left:50px;>
</div>

<div style="width:500px;height:100px;border:1px solid #000;">
    <p style="padding-left:50px;">
        Name: Dr. Khadija<br />
        Specification :Child Specialist<br />
        Clinic: GT road<br />
        Hospital:Fatima Memorial Hospital<br />
        @Html.ActionLink("Take Appoitment", "TakeAppoitment", "Patient")

    </p>
</div>

@Html.ActionLink("Back", "SelectDoctor", "Patient")

bookthedoctor/Views/Patient/DermatologistDetails.cshtml
@model BookMyDoctor.Models.BookMyDoctor.Models.RegisterViewModel

@{
    ViewBag.Title = "DermatologistDetails";
}

<h2><br />Following doctors are avalible for you</h2>

<div style="width:500px;height:100px;border:1px solid #000;">
    <p style="padding-left:50px;">
        Name: Dr. Maham<br />
        Specification :Dermatologist<br />
        Clinic: Model Town<br />
        Hospital:GangaRam Hospital Mall Road<br />
        @Html.ActionLink("Take Appoitment", "TakeAppoitment", "Patient")

    </p>
</div>

<div style="width:500px;height:100px;border:1px solid #000;">
    <p style="padding-left:50px;">
        Name: Dr. Hiba<br />
        Specification :Dermatologist<br />
        Clinic: Wapda Town<br />
        Hospital:Fatima Memorial Hospital<br />
        @Html.ActionLink("Take Appoitment", "TakeAppoitment", "Patient")

        </pstyle="padding-left:50px;>
</div>

<div style="width:500px;height:100px;border:1px solid #000;">
    <p style="padding-left:50px;">
        Name: Dr. Khadija<br />
        Specification :Dermatologist<br />
        Clinic: GT road<br />
        Hospital:Fatima Memorial Hospital<br />
        @Html.ActionLink("Take Appoitment", "TakeAppoitment", "Patient")

    </p>
</div>

@Html.ActionLink("Back", "SelectDoctor", "Patient")

bookthedoctor/Views/Patient/GynecologistDetails.cshtml
@model BookMyDoctor.Models.BookMyDoctor.Models.RegisterViewModel

@{
    ViewBag.Title = "GynecologistDetails";
}

<h2><br />Following doctors are avalible for you</h2>

<div style="width:500px;height:100px;border:1px solid #000;">
    <p style="padding-left:50px;">
        Name: Dr. Maham<br />
        Specification :Gynecologist<br />
        Clinic: Model Town<br />
        Hospital:GangaRam Hospital Mall Road<br />
        @Html.ActionLink("Take Appoitment", "TakeAppoitment", "Patient")

    </p>
</div>

<div style="width:500px;height:100px;border:1px solid #000;">
    <p style="padding-left:50px;">
        Name: Dr. Hiba<br />
        Specification :Gynecologist<br />
        Clinic: Wapda Town<br />
        Hospital:Fatima Memorial Hospital<br />
        @Html.ActionLink("Take Appoitment", "TakeAppoitment", "Patient")

        </pstyle="padding-left:50px;>
</div>

<div style="width:500px;height:100px;border:1px solid #000;">
    <p style="padding-left:50px;">
        Name: Dr. Khadija<br />
        Specification :Gynecologist<br />
        Clinic: GT road<br />
        Hospital:Fatima Memorial Hospital<br />
        @Html.ActionLink("Take Appoitment", "TakeAppoitment", "Patient")

    </p>
</div>

@Html.ActionLink("Back", "SelectDoctor", "Patient")

bookthedoctor/Views/Patient/Index.cshtml
@model BookMyDoctor.Models.BookMyDoctor.Models.RegisterViewModel

@{
    ViewBag.Title = "Index";
}

body background="doctors.jpg">

<h2>Index</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <h2 align="center">PATIENT REGISTRATION FORM</h2>
    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Choose", "SelectDoctor", "Patient")
</div>


<div>
    @Html.ActionLink("Back to List", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

bookthedoctor/Views/Patient/SelectDoctor.cshtml
@model BookMyDoctor.Models.BookMyDoctor.Models.RegisterViewModel

@{
    ViewBag.Title = "SelectDoctor";
}


<h2><br />WELCOME SELECT THE DOCTOR YOU WANT TO VISIT</h2>

<div style="width:500px;height:150px;border:1px solid #000;">
    <h3 style="padding-left:50px;">@Html.ActionLink( "DOCTOR", "ViewDoctorDetails", "Patient")</h3>
    <h5 style="padding-left:65px;">@Html.ActionLink("Cardiologists", "CardiologistsDetails", "Patient")</h5>
    <h5 style="padding-left:65px;">@Html.ActionLink("Child Specialist", "ChildSpecialistDetails", "Patient")</h5>
    <h5 style="padding-left:65px;">@Html.ActionLink("Dermatologist", "DermatologistDetails", "Patient")</h5>
    <h5 style="padding-left:65px;">@Html.ActionLink("Gynecologist", "GynecologistDetails", "Patient")</h5>
</div>

<div style="width:500px;height:65px;border:1px solid #000;">
    <h3 style="padding-left:50px;">@Html.ActionLink("DENTIST", "Index", "Home")</h3>

</div>

<div style="width:500px;height:65px;border:1px solid #000;">
    <h3 style="padding-left:50px;" >@Html.ActionLink("PSYCHOLOGIST", "Index", "Home")</h3>
    

</div>

bookthedoctor/Views/Patient/TakeAppoitment.cshtml
<!DOCTYPE html>
<html>
<body>
    <container>
        <h2 style="padding-top:34px;text-align:center;">
            CLINIC SHEDULE
        </h2>
        <pr>
            Clinic Name: Health is Wealth<br />
            Clinic Location: Block C , Model Town , Lahore
        </pr>
        <table style="width:100%">
            <tr>
                <th>DAY</th>
                <th>Time Slot</th>
                <th>Appoitment Status</th>
            </tr>
            <tr>
                <td>Monday</td>
                <td>12:00 pm - 3:00 pm</td>
                <td><button type="button" onclick="alert('Your request has been placed. Please wait for your response on your Email')">Take Appoitment</button>
            </tr>
            <tr>
                <td>Tuesday</td>
                <td>12:00 pm - 3:00 pm</td>
                <td><button type="button" onclick="alert('Your request has been placed. Please wait for your response on your Email')">Take Appoitment</button>
            </tr>
            <tr>
                <td>Wednesday</td>
                <td>12:00 pm - 3:00 pm</td>
                <td><button type="button" onclick="alert('Your request has been placed. Please wait for your response on your Email')">Take Appoitment</button>
            </tr>
            <tr>
                <td>Friday</td>
                <td>12:00 pm - 2:00 pm</td>
                <td><button type="button" onclick="alert('Your request has been placed. Please wait for your response on your Email')">Take Appoitment</button>
            </tr>
            <tr>
                <td>Saturday</td>
                <td>12:00 pm - 4:00 pm</td>
                <td><button type="button" onclick="alert('Your request has been placed. Please wait for your response on your Email')">Take Appoitment</button>
            </tr>

        </table>


        <h2 style="padding-top:34px;text-align:center;">
            HOSPITAL SHEDULE
        </h2>
        <pr>
            Hospital Name: Fatima Memorial Hospital<br />
            Hospital Location: Block A, Shadman Lahore
        </pr>
        <table style="width:100%">
            <tr>
                <th>DAY</th>
                <th>Time Slot</th>
                <th>Appoitment Status</th>
            </tr>
            <tr>
                <td>Monday</td>
                <td>6:00 pm - 10:00 pm</td>
                <td><button type="button" onclick="alert('Your request has been placed. Please wait for your response on your Email')">Take Appoitment</button>
            </tr>
            <tr>
                <td>Tuesday</td>
                <td>4:00 pm - 9:00 pm</td>
                <td><button type="button" onclick="alert('Your request has been placed. Please wait for your response on your Email')">Take Appoitment</button>
            </tr>
            <tr>
                <td>Wednesday</td>
                <td>5:00 pm - 8:00 pm</td>
                <td><button type="button" onclick="alert('Your request has been placed. Please wait for your response on your Email')">Take Appoitment</button>
            </tr>
            <tr>
                <td>Friday</td>
                <td>5:00 pm - 10:00 pm</td>
                <td><button type="button" onclick="alert('Your request has been placed. Please wait for your response on your Email')">Take Appoitment</button>
            </tr>
            <tr>
                <td>Saturday</td>
                <td>7:00 pm - 11:00 pm</td>
                <td><button type="button" onclick="alert('Your request has been placed. Please wait for your response on your Email')">Take Appoitment</button>
            </tr>

        </table>
    </container>
</body>
</html>

bookthedoctor/Views/Patient/ViewDoctorDetails.cshtml
@model BookMyDoctor.Models.BookMyDoctor.Models.RegisterViewModel

@{
    ViewBag.Title = "ViewDoctorDetails";
}

<h2><br />Following doctors are avalible for you</h2>

<div style="width:500px;height:100px;border:1px solid #000;">
    <p style="padding-left:50px;">
        Name: Dr. Maham<br />
        Specification :Cardiologist<br />
        Clinic: Model Town<br />
        Hospital:GangaRam Hospital Mall Road<br />
        @Html.ActionLink("Take Appoitment", "TakeAppoitment", "Patient")

    </p>
</div>

<div style="width:500px;height:100px;border:1px solid #000;">
    <p style="padding-left:50px;">
        Name: Dr. Hiba<br />
        Specification :Child Specialist<br />
        Clinic: Wapda Town<br />
        Hospital:Fatima Memorial Hospital<br />
        @Html.ActionLink("Take Appoitment", "TakeAppoitment", "Patient")

    </pstyle="padding-left:50px;>
</div>

<div style="width:500px;height:100px;border:1px solid #000;">
    <p style="padding-left:50px;">
        Name: Dr. Khadija<br />
        Specification :Dermatologist<br />
        Clinic: GT road<br />
        Hospital:Fatima Memorial Hospital<br />
        @Html.ActionLink("Take Appoitment", "TakeAppoitment", "Patient")

    </p>
</div>

@Html.ActionLink("Back", "SelectDoctor", "Patient")